### ISSUE TITLE
"Failed to fetch and parse JSON for endpoint" errors

### ISSUE THREAD

**Issue by cepm-nate** [procore/js-sdk-endpoints#9]
### Installation in Existing Project using NPM on Windows
`npm i @procore/js-sdk-endpoints --save-dev` worked.

### Usage

- Create 'lib' folder in root of project.
- Within 'lib' folder, create 'endpoints' folder.
- Run `node .\node_modules\@procore\js-sdk-endpoints\endpoints lib -i index.ts -d endpoints`
- Progress bar goes to random position between 65% and 95%.
- 'endpoints' folder fills up with many .ts files.
- Error (below) is shown.

### Errors
- `Failed to fetch and parse JSON for endpoint: payment application (owner invoice) line items failed at step: Fetch (node:5168) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://procore-api-documentation-staging.s3-website-us-east-1.amazonaws.com/master/payment-application-(owner-invoice)-line-items.json reason: Unexpected token < in JSON at position 0 .......etc`
- Same error above, but for various endpoints. So far I've hit:
  - payment application (owner invoice)
  - line item types (cost types)
  - requisition (subcontractor invoice)

### Questions
- Is there a new endpoints URL we should be using, or perhaps some JSON files are missing?

**Comment by cepm-nate** [comment]
I added a console.log() for the failed URL into the .catch area, and this is what it showed:
![image](https://user-images.githubusercontent.com/10284464/93616214-4a439400-f989-11ea-8397-77cb2a575fa8.png)

Upon sending a request to one of them directly, i get a 403 Forbidden error.

**Comment by brock-noah** [comment]
This repo has been updated with the fix. Next steps include updating the JS SDK and publishing. I'll post again when things are complete.
